name: CI

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create reports dir
        run: mkdir reports

      - name: Run tests
        env:

          CYRUS_DATA_DIR: ${{ github.workspace }}\tmp_data
        run: |
          pytest -q --maxfail=1 `
            --junitxml=reports/junit.xml `
            --html=reports/report.html --self-contained-html `
            --cov=. --cov-report=term-missing

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
